spring.application.name=Expense_Manager
spring.datasource.url=jdbc:mysql://localhost:3306/expense_manager
spring.datasource.username=root
spring.datasource.password=rootsql111

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error

jwt.apikey=yt40lwmhskXnTY3cdlECJ5T8iNxdE6IYgBnEpzssomLFPCaZmIsHEmxrlHTWh50Q
jwt.secretKey=yt40lwmhskXnTY3cdlECJ5T8iNxdE6IYgBnE_expense

jwt.accessToken-life=68000000
jwt.refreshToken-life=31104000000




spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

jwt.authorization=Authorized
jwt.apiKeyHeader=X-expense-api-key

# Only for testing! This disables the security filter for these paths
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.api-docs.path=/v3/api-docs